### ISSUE TITLE
Addition of KWOC report folder

### ISSUE THREAD

**Issue by championballer** [maze-runnar/interview-preparation-kit#105]
Do you think that a folder should be added to the repo, which contains the reports of all contributors who worked on this project in KWOC. That will allow for a centralised storage for all contributors for their reports, and the rebasing will also work well. Plus that would be great for future contributors to refer to in the future? @maze-runnar

**Comment by maze-runnar** [comment]
@championballer that is a great suggestion and also very good reference for future contributors .
Can you please share this issue on our communication channel so that contributors can discuss anything they want to :+1:
