### ISSUE TITLE
2D array solution not available in c++

### ISSUE THREAD

**Issue by CapTen101** [maze-runnar/interview-preparation-kit#111]
The first question of arrays ([2D Array](https://www.hackerrank.com/challenges/2d-array/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=arrays)) hasn't been solved in C++. The file is shown as empty. @maze-runnar Kindly look into it

**Comment by maze-runnar** [comment]
thanks, @CapTen101 for figuring it out, I am looking it out.

**Comment by maze-runnar** [comment]
Done with commit https://github.com/maze-runnar/interview-preparation-kit/commit/67e41b1acbbd5ef65d21f3cfe87e8904b1fc26f2
