### ISSUE TITLE
Add one more column in the table for Javascript initiate

### ISSUE THREAD

**Issue by RashakDude** [maze-runnar/interview-preparation-kit#63]
This will be divided into three parts -
* Easy
* Medium
* Hard
<br>
This will ultimately help the viewers of this repository to know the difficulty of the question in prior.

**Comment by championballer** [comment]
Makes sense to me. @maze-runnar What do you feel? Do you think the project should be extended to javascript as well, since that is one of the remaining widely used languages left?

**Comment by maze-runnar** [comment]
@championballer please initiate a js column and @RashakDude at the time no need to add difficulty level ,

**Comment by amit6663** [comment]
sir @maze-runnar can i work on this issue?

**Comment by maze-runnar** [comment]
Go ahead

**Comment by championballer** [comment]
@amit6663 Till when would you be able to open a PR for this?

**Comment by amit6663** [comment]
> @amit6663 Till when would you be able to open a PR for this?

sir @championballer, i'm facing problem in rebasing, so I spent more time. sir can you provide me exact link which solve rebasing.

**Comment by championballer** [comment]
#75 solves this. Good job @amit6663
