### ISSUE TITLE
We can add a new C language section for all the questions

### ISSUE THREAD

**Issue by sanskar28** [maze-runnar/interview-preparation-kit#85]

**Comment by maze-runnar** [comment]
@championballer what you think about this ?

**Comment by championballer** [comment]
In my personal opinion we should complete the solution set for the languages that we are currently working on till the winter of code ends and then we can focus on the expansion to other languages. Focusing on too many languages at the same time might not be a great idea, IMO.

**Comment by maze-runnar** [comment]
ok , so i am closing issue this !
