### ISSUE TITLE
Birthday Cake Candies problem not a part of interview kit

### ISSUE THREAD

**Issue by RashakDude** [maze-runnar/interview-preparation-kit#93]
I checked that the interview preparation kit on the HackerRank contains only four problems and found that ' Birthday Cake Candies is not a part of it '.

**Comment by championballer** [comment]
Yeah you are right. I guess it got added in some confusion. You want to work on removing this?

**Comment by RashakDude** [comment]
@championballer Yes I can. BTW, this contributing experience was great with you. I really enjoyed. Thanks :-)

**Comment by championballer** [comment]
Same here @RashakDude
